// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace iFlota.Forms.Localizacion {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecursosTexto {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosTexto() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("iFlota.Forms.Localizacion.RecursosTexto", typeof(RecursosTexto).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Splash_PasswordTitleLabel {
            get {
                return ResourceManager.GetString("Splash_PasswordTitleLabel", resourceCulture);
            }
        }
        
        public static string Splash_SkipSignIn {
            get {
                return ResourceManager.GetString("Splash_SkipSignIn", resourceCulture);
            }
        }
        
        public static string Splash_SignIn {
            get {
                return ResourceManager.GetString("Splash_SignIn", resourceCulture);
            }
        }
        
        public static string Splash_Title {
            get {
                return ResourceManager.GetString("Splash_Title", resourceCulture);
            }
        }
        
        public static string Splash_UsernameTitleLabel {
            get {
                return ResourceManager.GetString("Splash_UsernameTitleLabel", resourceCulture);
            }
        }
    }
}
